name: Bug Report
description: Report a new bug
labels: ["bug"]
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: Please fill out this form to help us reproduce the bug and fix it.
  - type: textarea
    attributes:
      label: Describe the issue
      description: Explain the issue you are facing in details
      placeholder: When I do {something}, {something weird} happens
    validations:
      required: true