name: Bug Report
description: Report a new bug
labels: ["bug"]
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: Please fill out this form to help us reproduce the bug and fix it.
