name: New Feature
description: Suggest or request a new feature
labels: ["enhancement"]
title: "[Feature]: "
body:
  - type: markdown
    attributes:
      value: Please fill out the form to properly describe the new feature you are suggesting.
  - type: textarea
    attributes:
      label: Describe the feature
      placeholder: A button in the screen X that allows to do Y
    validations:
      required: true
  - type: textarea
    attributes:
      label: It should be implemented because
      placeholder: It will allow to do Y that is needed for Z
  - type: textarea
    attributes:
      label: Additional context (optional)
      placeholder: Put here any other information such as screenshots or videos or links that you think is necessary.
  - type: textarea
    attributes:
      label: If you have a timeframe/deadline in mind for this feature, please specify it below
      placeholder: This feature needs to be implemented before yyyy-mm-dd
  - type: markdown
    attributes:
      value: Thanks for your suggestion! Let's see together if it can be implemented.